### ISSUE TITLE
Icon doesn't shows

### ISSUE THREAD

**Issue by devashish2024** [S-Vishwaja/Study_Space#5]
Icon doesn't shows
It's Because you're using the <img> tag method that doesn't sets icons.
Use this method and change the "href"'s value to the Image icon you'd like to set.
This will not needs the Closing link tag.
If you want to know How to link CSS or JS files, tell me.
Include this in head tag.
```html
<link rel="icon" href="YourImageIconComeHere">
```

**Comment by Sachiru-Perera** [comment]
How to add an icon?

**Comment by Sachiru-Perera** [comment]
Oh..ty!

**Comment by devashish2024** [comment]
Replace the "YourImageIconComeHere" with your icon url. [ Supports ONLY SVG, PNG, JPG, JFIF. ]
```html
<link rel="icon" href="YourImageIconComeHere">
```

**Comment by devashish2024** [comment]
Will this works?
